"use client";

import "./globals.css";
import { Inter } from "next/font/google";

import Header from "@/components/common/Header";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Providers>
      <Header />
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          {children}
        </body>
      </html>
    </Providers>
  );
}
